### ISSUE TITLE
Request: heatmap

### ISSUE THREAD

**Issue by SpiritAxolotl** [concord-consortium/codap#1141]
I'm working on a statistics project, and it's hard to see a correlation between quantitative data when the data is very discreet (because multiple points overlap).
I request that the datapoints have some sort of color value that they more closely resemble if they are closer together.

**Comment by bfinzer** [comment]
Hello,I have an idea that might (sort of) work for this situation. If you wouldn’t mind posting to the CODAP Help Forum, I’d be pleased to post a response where others in the CODAP community will be able to see it.Thanks for the question, and for posting on the forum. (And let me know if you have any trouble posting. Sometimes it can be a bit finicky.)BillOn Feb 29, 2024, at 8:07 AM, Spax ***@***.***> wrote:﻿
I'm working on a statistics project, and it's hard to see a correlation between quantitative data when the data is very discreet (because multiple points overlap).
I request that the datapoints have some sort of color value that they more closely resemble if they are closer together.

**Comment by SpiritAxolotl** [comment]
https://codap.concord.org/forums/topic/heatmap/
